#!/bin/sh
FILE="$HOME/.config/scripts/bookmark-list"

add_bookmark() {
    url=$(wl-paste -p)
    desc=$(echo | bemenu -p "Desc." )
    echo "$url  # $desc" >> $FILE
    notify-send "Bookmarked" "$url"
}

bookmark () {
    cat $FILE | bemenu -l10 -i -C | awk '{print $1}' | tr -d "\n" | wl-copy
    wtype $(wl-paste)
}

case $1 in
    "-a")
        add_bookmark
        ;;
    *)
        bookmark
        ;;
esac

