#!/bin/sh

iDIR=""                 # Icon directory

# notify function
notify () {
    # send someblock update signal
    pkill -RTMIN+13 someblocks      # 13 for brightness
    # send notify
    notify-send -h string:x-canonical-private-synchronous:anything -i "$DIR/$FILE" -u normal "Brightness" "$(get_brightness)%"
}
# get icon according to brightness
get_icon () {
    brightness=$(get_brightness)
    if [[ $brightness -gt 80 ]]; then
        echo
    fi
}
# get brightness in percentage
get_brightness () {
    printf $(( $(brightnessctl g)*100/$(brightnessctl m) )) 
}
# increment brightness with 2%
inc_brightness () {
    brightnessctl -q s +5%
    notify $(get_brightness)
}
# decrement brightness with 2%
dec_brightness () {
    brightnessctl -q s 5%-
    notify $(get_brightness)
}
# filter arguments
case $1 in 
    "-i" | "--inc")
        inc_brightness
        ;;
    "-d" | "--dec")
        dec_brightness
        ;;
    *)
        get_brightness
        ;;
esac
# Exit code
exit 0

