#!/bin/sh

iDIR=""

get_icon() {
    volume=$(get_volume)
    if [[ volume -gt 80 ]]; then
        return "$iDir/volume80p"
    elif [[ volume -gt 60 ]]; then
        return "$iDir/volume80p"
    elif [[ volume -gt 40 ]]; then
        return "$iDir/volume80p"
    elif [[ volume -gt 20 ]]; then
        return "$iDir/volume80p"
    else
        return "$iDir/vol"
    fi
}
notify () {
    pkill -RTMIN+10 someblocks
    if get_muted; then
        notify-send -h string:x-canonical-private-synchronous:anything -i "$iDIR/muted" -u normal "Muted"
    else
        notify-send -h string:x-canonical-private-synchronous:anything -i "$(get_icon)" -u normal "Volume" "$(get_volume)%"
    fi
}

get_muted() {
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

get_volume () {
    pactl get-sink-volume @DEFAULT_SINK@ | head -n 1 | cut -f 2 -d '/' | cut -d '%' -f 1 | xargs
}

inc_volume () {
    # unmute if it is muted
    amixer -D pipewire set Master on > /dev/null
    # increase volume 2%
    pactl set-sink-volume @DEFAULT_SINK@ +2% > /dev/null
    notify
}

dec_volume () {
    # unmute if it is muted
    amixer -D pipewire set Master on > /dev/null
    # decrease volume 2%
    pactl set-sink-volume @DEFAULT_SINK@ -2% > /dev/null
    notify
}

toggle_mute () {
    amixer -D pipewire set Master 1+ toggle > /dev/null
    notify
}

case $1 in
    "-i" | "--inc")
        inc_volume
        ;;
    "-d" | "--dec")
        dec_volume
        ;;
    "-m"| "--mute")
        toggle_mute
        ;;
    *)
        get_volume
esac

