#!/bin/sh

DIR="$(xdg-user-dir PICTURES)/Screenshoot"
FILE=$(date +'%Y%e%d-%s.png')

mkdir -p "$DIR"
grim -g "$(slurp)" -l 3 - | tee "$DIR/$FILE" | wl-copy

if [ -f "$DIR/$FILE" ]; then
    notify-send -i "$DIR/$FILE" -u normal "Screenshoot Saved" "$FILE"
else
    notify-send -u normal "Screenshoot Failed" "Unable to save screenshoot"
fi
