#!/bin/sh

DIR="$(xdg-user-dir PICTURES)/Screenshot"
FULL_FILE=$(date +'%Y%e%d-%s.png')
SHORT_FILE=$(date +'%s.png')

mkdir -p "$DIR"
GEOMETRY=$(slurp) || exit 1

TEMP_FILE="/tmp/screenshot_$SHORT_FILE"
grim -g "$GEOMETRY" -l 3 - > "$TEMP_FILE" || exit 1

NAME="$(wofi --dmenu -p "Enter name for screenshot" -l 0)_$SHORT_FILE" || NAME="$FULL_FILE"
mv "$TEMP_FILE" "$DIR/$NAME" || exit 1
wl-copy < "$DIR/$NAME"

if [ -s "$DIR/$NAME" ]; then
    notify-send -i "$DIR/$NAME" -u normal "Screenshot Saved" "$NAME"
else
    notify-send -u normal "Screenshot Failed" "Unable to save screenshot"
    exit 1
fi
