#!/bin/sh

iDIR="$HOME/.config/"              # Icon directory

# Script to toggle aeroplane mode
if nmcli r wifi | grep -qx "enabled"; then
        rfkill block all && notify-send -i $iDIR/airplane "Aeroplane mode ON"
    else
        rfkill unblock all && notify-send -i $iDIR/wifi "Aeroplane mode OFF"
fi
# Setting wallpaper
swaybg -mfill -o* -i "$rFILE"

# Exit code
exit 0

