#!/bin/bash

cd ~/Repos

selected=$(find * -maxdepth 1 -type d | fzf --height 40% --layout=reverse \
    --border-label="Search Projects" --border=rounded)
session_name=$(basename "$selected" | sed 's/[^a-zA-Z0-9]/_/g')

if [ -z "$selected" ]; then
    echo "Nothing selected!"
    exit 0
fi

cd "$selected"

if ! tmux has-session 2>/dev/null; then
    tmux new-session -s "$session_name" -c "$HOME/Repos/$selected"
    exit 0
fi

if tmux has-session -t "$session_name" 2>/dev/null; then
    window_index=$(tmux new-window -t "$session_name" -c "$HOME/Repos/$selected" -P -F "#{window_index}")
    tmux select-window -t "$session_name:$window_index"
    tmux attach-session -t "$session_name"
else
    tmux new-session -d -s "$session_name" -c "$HOME/Repos/$selected"
    tmux attach-session -t "$session_name"
fi
