#!/bin/sh

DIR="$(xdg-user-dir PICTURES)/Screenshoot"
FILE=$(date +"%Y%e%d-%s.png")
iDIR=""

notify () {
    if [[ -f "$DIR/$FILE" ]]; then
        notify-send -i "$DIR/$FILE" -u normal "Screenshoot Saved" "$FILE"
    else
        notify-send -i "$iDIR/failed.png" -u normal "Screenshoot Failed" "Unable to save screenshoot"
    fi
}

shoot_screen () {
    grim "$DIR/$FILE" -l 3| wl-copy
    notify
}

shoot_area () {
    grim -g "$(slurp)" -l 3 "$DIR/$FILE"| wl-copy
    notify
}

case $1 in
    "-a" | "--get")
        shoot_area
        ;;
    "-f" | "--full")
        shoot_screen
        ;;
    *)
        shoot_area
        ;;
esac

