#!/bin/sh

DIR="$(xdg-user-dir PICTURES)/Screenshot/"
ICON_DIR="$XDG_CONFIG_HOME/.assets/Icons/others/"
FULL_FILE=$(date +'%Y%e%d-%s.png')
SHORT_FILE=$(date +'%s.png')

notify_and_exit () {
    notify-send -i "$ICON_DIR/error.png" -u normal "Screenshot Failed" "Unable to save screenshot"
    exit 1
}

if [ "$1" == "--edit" ]; then
    grim -g "$(slurp)" - | swappy -f -
    exit 0
fi

mkdir -p "$DIR"
GEOMETRY=$(slurp) || notify_and_exit

TEMP_FILE="/tmp/screenshot_$SHORT_FILE"
grim -g "$GEOMETRY" -l 3 - > "$TEMP_FILE" || notify_and_exit

NAME="$(echo "$FULL_FILE" | wmenu -p "Enter name for screenshot" -l 1)_$SHORT_FILE" || NAME="$FULL_FILE"
mv "$TEMP_FILE" "$DIR/$NAME" || notify_and_exit
wl-copy < "$DIR/$NAME"

if [ -s "$DIR/$NAME" ]; then
    notify-send -i "$DIR/$NAME" -u normal "Screenshot Saved" "$NAME"
    exit 0
else
    notify_and_exit
fi
