#!/bin/bash
# #########################################################
# MAPPINGS ################################################
# #########################################################
# MICE
BROWSER="librewolf"
MENU="wofi -Sdrun -L16"
MOD_KEY=Mod4

riverctl map normal $MOD_KEY BRACKETLEFT spawn "river-shifttags --shifts -1"
riverctl map normal $MOD_KEY BRACKETRIGHT spawn "river-shifttags"
riverctl map normal $MOD_KEY+Control B spawn "$BROWSER"
riverctl map normal $MOD_KEY N spawn "riverctl focus-output next"
riverctl map normal $MOD_KEY O spawn "wofi -Sdrun -L16"
riverctl map normal $MOD_KEY S spawn "riverctl send-to-output next"
riverctl map normal $MOD_KEY+Shift Equal spawn "zoom-wm"
riverctl map normal $MOD_KEY+Control W spawn "swaylock"
riverctl map normal $MOD_KEY+Control+Shift Y spawn "systemctl suspend"
riverctl map normal $MOD_KEY+Shift B spawn "$BROWSER --private-window"
riverctl map normal $MOD_KEY+Shift W spawn "random-wallpaper"
riverctl map normal $MOD_KEY+Control W spawn "random-wallpaper --remote"
riverctl map normal $MOD_KEY+Shift S spawn "screenshot"
riverctl map normal $MOD_KEY+Shift Return spawn "footclient"
riverctl map normal $MOD_KEY+Shift Right spawn "river-shifttags"

# FUNCTIONS
riverctl map normal $MOD_KEY+Shift C close
riverctl map normal $MOD_KEY+Control+Alt Q exit
# Focus next/previous view in the layout stack
riverctl map normal $MOD_KEY J focus-view next
riverctl map normal $MOD_KEY K focus-view previous
# Swap the focused view with the next/previous view in the layout stack
riverctl map normal $MOD_KEY+Shift J swap next
riverctl map normal $MOD_KEY+Shift K swap previous
# Focus the next/previous output
riverctl map normal $MOD_KEY Period focus-output next
riverctl map normal $MOD_KEY Comma focus-output previous
# Send the focused view to the next/previous output
riverctl map normal $MOD_KEY+Shift Period send-to-output next
riverctl map normal $MOD_KEY+Shift Comma send-to-output previous
# Bump the focused view to the top of the layout stack
riverctl map normal $MOD_KEY Return zoom
# Increase/Decrease the main ratio of rivertile
riverctl map normal $MOD_KEY H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $MOD_KEY L send-layout-cmd rivertile "main-ratio +0.05"
# Increment/Decrement the main count of rivertile
riverctl map normal $MOD_KEY+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $MOD_KEY+Shift L send-layout-cmd rivertile "main-count -1"
# Move views
riverctl map normal $MOD_KEY+Alt H move left 100
riverctl map normal $MOD_KEY+Alt J move down 100
riverctl map normal $MOD_KEY+Alt K move up 100
riverctl map normal $MOD_KEY+Alt L move right 100
# Snap views to screen edges
riverctl map normal $MOD_KEY+Control+Alt H snap left
riverctl map normal $MOD_KEY+Control+Alt J snap down
riverctl map normal $MOD_KEY+Control+Alt K snap up
riverctl map normal $MOD_KEY+Control+Alt L snap right
# To resize views
riverctl map normal $MOD_KEY+Alt+Shift H resize horizontal -100
riverctl map normal $MOD_KEY+Alt+Shift J resize vertical 100
riverctl map normal $MOD_KEY+Alt+Shift K resize vertical -100
riverctl map normal $MOD_KEY+Alt+Shift L resize horizontal 100
# Toggle float
riverctl map normal $MOD_KEY+Shift Space toggle-float
# Toggle fullscreen
riverctl map normal $MOD_KEY F toggle-fullscreen
# $MOD_KEY+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $MOD_KEY Up send-layout-cmd rivertile "main-location top"
riverctl map normal $MOD_KEY Right send-layout-cmd rivertile "main-location right"
riverctl map normal $MOD_KEY Down send-layout-cmd rivertile "main-location bottom"
riverctl map normal $MOD_KEY Left send-layout-cmd rivertile "main-location left"

# MOUSE
# $MOD_KEY + Left Mouse Button to move views
riverctl map-pointer normal $MOD_KEY BTN_LEFT move-view
# $MOD_KEY + Right Mouse Button to resize views
riverctl map-pointer normal $MOD_KEY BTN_RIGHT resize-view
# $MOD_KEY + Middle Mouse Button to toggle float
riverctl map-pointer normal $MOD_KEY BTN_MIDDLE toggle-float

# #########################################################
# TAGS CONFIGURATION ######################################
# #########################################################
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # $MOD_KEY+[1-9] to focus tag [0-8]
    riverctl map normal $MOD_KEY $i set-focused-tags $tags

    # $MOD_KEY+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $MOD_KEY+Shift $i set-view-tags $tags

    # $MOD_KEY+Control+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $MOD_KEY+Control $i toggle-focused-tags $tags

    # $MOD_KEY+Shift+Control+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $MOD_KEY+Control+Shift $i toggle-view-tags $tags
done
# for work ans scratchpad
tags=$((1 << 9));
riverctl map normal $MOD_KEY D set-focused-tags $tags
riverctl map normal $MOD_KEY+Shift D set-view-tags $tags
riverctl map normal $MOD_KEY+Control D toggle-focused-tags $tags
tags=$((1 << 10));
riverctl map normal $MOD_KEY A set-focused-tags $tags
riverctl map normal $MOD_KEY+Shift A set-view-tags $tags
riverctl map normal $MOD_KEY+Control A toggle-focused-tags $tags
# $MOD_KEY+0 to focus all tags & Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 12) - 1))
riverctl map normal $MOD_KEY 0 set-focused-tags $all_tags
riverctl map normal $MOD_KEY+Shift 0 set-view-tags $all_tags

# Media Keys
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    # riverctl map $mode None XF86Eject spawn "eject -T"

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map $mode None XF86AudioRaiseVolume spawn "pactl set-sink-volume @DEFAULT_SINK@ +5%"
    riverctl map $mode None XF86AudioLowerVolume spawn "pactl set-sink-volume @DEFAULT_SINK@ -5%"
    riverctl map $mode None XF86AudioMute spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPlay spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev spawn "playerctl previous"
    riverctl map $mode None XF86AudioNext spawn "playerctl next"

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp spawn "brightnessctl set +5%"
    riverctl map $mode None XF86MonBrightnessDown spawn "brightnessctl set 5%-"
done

# #########################################################
# GENERAL CONFIGURATION ###################################
# #########################################################

# Where new windows starts
riverctl attach-mode top

# background color
# riverctl background-color 0x08a7bf

# focused border color
riverctl border-color-focused 0x33bbbb

# unfocused border color
riverctl border-color-unfocused 0xaaaaaa

# urgent border color
riverctl border-color-urgent 0xff5555

# border width
riverctl border-width 1

# focus follow cursor
riverctl focus-follows-cursor always

# hide cursor when timeout
riverctl hide-cursor timeout 30000 # in millisecond


# #########################################################
# INPUT CONFIGURATION #####################################
# #########################################################

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Set keyboard layout to UK
riverctl keyboard-layout gb

# Enable natural scroll
riverctl input pointer-1267-91-Elan_Touchpad natural-scroll enabled
riverctl input pointer-1267-91-Elan_Touchpad disable-while-typing disabled

# Enable tap to click
riverctl input pointer-1267-91-Elan_Touchpad tap enabled

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -view-padding 0 -outer-padding 0 &
riverctl spawn "yambar" &
riverctl spawn "random-wallpaper" &
riverctl spawn "mako" &
# riverctl spawn "killall pipewire ; pipewire" &
riverctl spawn "wlsunset -t 4500 -T 5000" &
riverctl spawn "foot -s" &
riverctl spawn "swayidle -w timeout 600 'notify-send \"Trying to lock\"' timeout 660 'swaylock'" &
riverctl rule-add -app-id firefox ssd
riverctl rule-add ssd
