#!/bin/sh

DIR="$(xdg-user-dir PICTURES)/Screenshot"
FULL_FILE=$(date +'%Y%e%d-%s.png')
SHORT_FILE=$(date +'%s.png')

mkdir -p "$DIR"
GEOMETRY=$(slurp) || exit 1

NAME="$(wofi --dmenu -p "Enter name for screenshot" -l 0)_$SHORT_FILE" || NAME="$FULL_FILE"
grim -g "$GEOMETRY" -l 3 - | tee "$DIR/$NAME" | wl-copy

if [ -s "$DIR/$NAME" ]; then
    notify-send -i "$DIR/$NAME" -u normal "Screenshot Saved" "$NAME"
else
    notify-send -u normal "Screenshot Failed" "Unable to save screenshot"
    exit 1
fi
